# Github workflow to test compositions
name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  LILYPOND_VERSION: 2.25.16
  ABJAD_COMMIT: fbcf8473bca0c4b008cd694fc30f0f62561d1e55
  NAUERT_COMMIT: 174145292b9418bd2fc78e442552eb8961d0810d
  PANG_COMMIT: e0f14587783dae33840ed48b934c89d61cad7fe1
  ABJAD_PATH: /tmp/abjad
  NAUERT_PATH: /tmp/abjad-ext-nauert
  PANG_PATH: /tmp/pang

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install LilyPond
      run: |
        lilypond_archive=lilypond-${LILYPOND_VERSION}-linux-x86_64.tar.gz
        lilypond_url=https://gitlab.com/lilypond/lilypond/-/releases
        lilypond_url=${lilypond_url}/v${LILYPOND_VERSION}/downloads/${lilypond_archive}
        echo ${lilypond_url}
        cd /tmp
        wget -q ${lilypond_url}
        tar -xf ${lilypond_archive}
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip coverage
    - name: Log environment variable(s)
      run: |
        echo $PATH
    - name: Install Abjad
      run: |
        # install without development dependencies
        git clone https://github.com/Abjad/abjad.git /tmp/abjad
        cd /tmp/abjad
        git checkout ${ABJAD_COMMIT}
        pip install /tmp/abjad
    - name: Install Nauert
      run: |
        git clone https://github.com/Abjad/abjad-ext-nauert.git ${NAUERT_PATH}
        pip install ${NAUERT_PATH}
    - name: Install Pang
      run: |
        git clone https://github.com/nivlekp/pang.git ${PANG_PATH}
        pip install ${PANG_PATH}
    - name: Install dependencies
      run: |
        export PATH=/tmp/lilypond-${LILYPOND_VERSION}/bin:/home/runner/bin:$PATH
        python -m pip install -e .[test]
        black --version
        flake8 --version
        isort --version
        pip --version
        pytest --version
        lilypond --version
    - name: Install LuaLaTeX
      run: |
        sudo apt update
        sudo apt install -y texlive-latex-base texlive-fonts-recommended
        sudo apt install -y texlive texlive-latex-extra texlive-luatex
        lualatex --version
    - name: Checks and Tests
      run: |
        export PATH=/tmp/lilypond-${LILYPOND_VERSION}/bin:/home/runner/bin:$PATH
        export MYPYPATH=$MYPYPATH:${ABJAD_PATH}
        export MYPYPATH=$MYPYPATH:${NAUERT_PATH}
        export MYPYPATH=$MYPYPATH:${PANG_PATH}
        make black-check
        make flake8
        make isort-check
        make pytest
    - name: Test Segments
      run: |
        export PATH=/tmp/lilypond-${LILYPOND_VERSION}/bin:/home/runner/bin:$PATH
        export PANG_PATH=${PANG_PATH}
        make test-sections
    - name: Test Score
      run: |
        export PATH=/tmp/lilypond-${LILYPOND_VERSION}/bin:/home/runner/bin:$PATH
        export PANG_PATH=${PANG_PATH}
        make test-score
        make full-score
    - name: Upload Full Score
      uses: actions/upload-artifact@v4
      with:
        name: full-score
        path: unicorns/builds/score/score.pdf
        compression-level: 0
